// Code generated by internal/gen. DO NOT EDIT.

package main

// Tool describes one entry in the toolbox's tool table.
type Tool struct {
	Name string
	Role string
}

// generatedTools is sorted by Name; see internal/gen/main.go.
var generatedTools = []Tool{
	{Name: "benchstat", Role: "compare statistical summaries of benchmark runs"},
	{Name: "delve", Role: "the Go debugger (dlv)"},
	{Name: "go generate", Role: "run source-code generators referenced by directive"},
	{Name: "go vet", Role: "report suspicious constructs the compiler allows"},
	{Name: "gofmt", Role: "format Go source files"},
	{Name: "gofumpt", Role: "a stricter superset of gofmt"},
	{Name: "golangci-lint", Role: "run many linters through one driver"},
	{Name: "govulncheck", Role: "cross-reference dependencies against the Go vuln DB"},
	{Name: "pprof", Role: "profile CPU, heap, and goroutine activity"},
	{Name: "staticcheck", Role: "advanced static analysis and unused-code detection"},
}
